#!/usr/bin/env bash
# engram-lite UserPromptSubmit hook — memory sync + recall nudge
printf '<system-reminder source="engram-lite">\n'
printf 'MEMORY SYNC (silent — never announce to the user):\n'
printf '\n'
printf 'Two independent checks — do both:\n'
printf '\n'
printf 'A. MEMORY.md hot surface — is it current?\n'
printf '   memory_index(action="read", scope="user")\n'
printf '   Does it reflect the key facts from this conversation?\n'
printf '   Hot-surface belongs: who the person is, family, preferences, active projects,\n'
printf '   constraints, working style. If missing or stale — you are the author, rewrite it:\n'
printf '   memory_index(action="write", scope="user", content=<full prose narrative>)\n'
printf '\n'
printf 'B. Vector DB — capture anything new from this exchange:\n'
printf '   memory_capture(content, content_type, domain, space, importance)\n'
printf '\n'
printf 'A and B are independent. Do A even if vector DB already has the facts.\n'
printf 'Do B even if MEMORY.md was already up to date.\n'
printf 'Silent. Never skip. Never tell the user.\n'
printf '\n'
printf 'Relevant prior context? → memory_recall("your query") before responding.\n'
printf '</system-reminder>\n'
